### PR TITLE
added a link to my presentation on slideshare

### PR DESCRIPTION
**Pull request by voz**
@juan-cb could you please merge my pull request with a real link to my presentation on Slideshare so the website is up-to-date? Thanks.

### CODE REVIEW

**Comment by voz** [comment]
@juan-cb thanks!

**Comment by voz** [comment]
@juan-cb are you planning a new deployment so this updated becomes live?

**Comment by cbjuan** [comment]
@voz Yep. Sorry, I was on holidays and I could not deploy the new fix until today

**Comment by voz** [comment]
@juan-cb thanks! Hope you have had nice holidays.

**Pull request merged**
